source 'http://rubygems.org'

group :default do
  gem 'rack', "~> 1.5.2"
  gem 'rake', "~> 10.3.2"
  gem 'grape', '~> 0.7.0'
  gem 'activerecord', '~> 5.2.4', '>= 5.2.4.3', :require => "active_record"
  gem 'json', '~> 1.8.1'
  gem 'grape-swagger', '>= 0.7.2'
  gem 'rack-cors', :require => 'rack/cors'
  gem 'mysql2', "~> 0.3.16"
  gem "schema_plus", "~> 1.5.1"
end

group :test, :development do
  gem 'rspec'
  gem 'rack-test', require: "rack/test"
  gem 'shotgun'
  gem 'racksh'
end