source 'http://rubygems.org'

group :default do
  gem 'rack', '~> 2.1.3'
  gem 'rake', "~> 10.3.2"
  gem 'grape', '~> 0.7.0'
  gem 'activerecord', "~> 3.2.18", :require => "active_record"
  gem 'json', '~> 1.8.1'
  gem 'grape-swagger', '>= 0.7.2'
  gem 'rack-cors', :require => 'rack/cors'
  gem 'mysql2', "~> 0.3.16"
  gem "schema_plus", "~> 1.5.1"
end

group :test, :development do
  gem 'rspec'
  gem 'rack-test', '>= 0.6.2', require: "rack/test"
  gem 'shotgun', '>= 0.9'
  gem 'racksh', '>= 1.0.0'
end